"""Audit exported/edited image provenance against their symbol tables.

Qualified image names join on exact (character ID, class) identity. Images
whose filenames omit that identity must resolve through an ActionScript Embed
or have an explicit, evidence-backed disposition; unexplained assets remain
gaps. This is source-coverage evidence, not a Godot conversion claim.
"""

from __future__ import annotations

import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "development/inventory/reference_inventory.json"
EXTRACTED = ROOT / "development/extracted/full-20260908"
EDITED_EXPORT = ROOT / "development/extracted/default-current"
OUTPUT = ROOT / "development/inventory/asset_provenance_audit.json"
MEDIA_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
QUALIFIED_NAME = re.compile(r"^(?P<id>\d+)_(?P<class>.+)\.(?:png|jpg|jpeg|bmp|webp)$", re.IGNORECASE)
EMBED_CLASS = re.compile(
    r"\[Embed\s*\(\s*source\s*=\s*['\"]/_assets/(?P<asset>[^'\"]+)['\"]\s*\)\s*\]"
    r"\s*public\s+class\s+(?P<class>[A-Za-z_$][\w$]*)",
    re.IGNORECASE,
)
PACKAGE = re.compile(r"\bpackage\s*([\w.]*)\s*\{", re.IGNORECASE)

# User-confirmed Minion Maker output: preserve it in the source inventory, but
# keep it outside the reference game's asset-coverage denominator.
USER_TEST_FIXTURES = {
    "1792_Utilities.SpriteHandler_eeveeMinion.png": {
        "kind": "user_confirmed_test_fixture",
        "reason": "The user confirmed this Eevee image was generated by their Minion Maker test and is not reference-game content.",
    }
}

# Supplemental files are retained and reported, not misrepresented as symbol
# exports. Each disposition names verifiable runtime/embedding evidence.
SUPPLEMENTAL_SOURCE_ASSETS = {
    "mainMenu_modMenuBackground.png": {
        "kind": "unqualified_unembedded_source_variant",
        "related_export": "1682_Utilities.SpriteHandler_mainMenu_modMenuBackground.png",
        "character_id": 1682,
        "qualified_class": "Utilities.SpriteHandler_mainMenu_modMenuBackground",
        "wrapper": "script/scripts/Utilities/SpriteHandler_mainMenu_modMenuBackground.as",
        "runtime_callsite": "script/scripts/MainMenu/ModMenu.as",
        "runtime_call": 'CreateSprite("mainMenu_modMenuBackground")',
        "reason": (
            "The same-name runtime handler is registered as character 1682 and its "
            "ActionScript Embed uses the qualified export. This additional source "
            "image is not itself embedded by a handler, so it is retained as a "
            "supplemental source variant rather than counted as an exact export."
        ),
    }
}


def symbols(path: Path) -> set[tuple[int, str]]:
    result: set[tuple[int, str]] = set()
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        for row in csv.reader(file, delimiter=";"):
            if len(row) >= 2 and row[0].isdigit():
                result.add((int(row[0]), row[1]))
    return result


def media_files(path: Path) -> dict[str, Path]:
    return {
        file.name: file
        for file in path.iterdir()
        if file.is_file() and file.suffix.lower() in MEDIA_EXTENSIONS
    }


def embedded_assets(script_root: Path) -> dict[str, set[str]]:
    """Map each embedded filename to its exact qualified ActionScript class."""
    result: dict[str, set[str]] = defaultdict(set)
    for script in script_root.rglob("*.as"):
        source = script.read_text(encoding="utf-8-sig", errors="replace")
        package_match = PACKAGE.search(source)
        package_name = package_match.group(1) if package_match else ""
        for match in EMBED_CLASS.finditer(source):
            qualified_class = f"{package_name}.{match.group('class')}" if package_name else match.group("class")
            result[Path(match.group("asset")).name].add(qualified_class)
    return result


def identity_for_name(name: str) -> tuple[int, str] | None:
    match = QUALIFIED_NAME.fullmatch(name)
    if match is None:
        return None
    return int(match.group("id")), match.group("class")


def main() -> None:
    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    reference = Path(inventory["reference_root"])
    original_images = media_files(EXTRACTED / "image")
    edited_images = media_files(reference / "source/images")
    original_symbols = symbols(EXTRACTED / "symbolClass/symbols.csv")
    edited_symbols = symbols(reference / "source/symbolClass/symbols.csv")
    original_embeds = embedded_assets(EXTRACTED / "script/scripts")
    edited_embeds = embedded_assets(EDITED_EXPORT / "script/scripts")
    counts: Counter[str] = Counter()
    gaps: list[dict[str, object]] = []
    resolutions: list[dict[str, object]] = []
    exclusions: list[dict[str, str]] = []

    def resolve_unqualified(
        name: str,
        path: Path,
        *,
        side: str,
        symbols_table: set[tuple[int, str]],
        embed_table: dict[str, set[str]],
    ) -> None:
        handlers = sorted(embed_table.get(name, set()))
        identities = sorted(
            (character_id, qualified_class)
            for character_id, qualified_class in symbols_table
            if qualified_class in handlers
        )
        if not handlers or not identities:
            gaps.append({
                "kind": f"{side}_unqualified_unresolved",
                "file": name,
                "source": str(path),
                "embedded_handlers": handlers,
                "exact_symbol_identities": [list(identity) for identity in identities],
            })
            return
        unresolved_handlers = sorted(set(handlers) - {identity[1] for identity in identities})
        if unresolved_handlers:
            gaps.append({
                "kind": f"{side}_unqualified_handler_missing_symbol",
                "file": name,
                "source": str(path),
                "handlers": unresolved_handlers,
            })
            return
        counts[f"{side}_unqualified_embed_resolved_images"] += 1
        counts[f"{side}_unqualified_embed_resolved_identities"] += len(identities)
        resolutions.append({
            "kind": "shared_embedded_resource",
            "side": side,
            "file": name,
            "source": str(path),
            "handler_classes": handlers,
            "exact_symbol_identities": [
                {"character_id": identity[0], "qualified_class": identity[1]}
                for identity in identities
            ],
        })

    for name, path in sorted(original_images.items()):
        counts["original_image_files"] += 1
        identity = identity_for_name(name)
        if identity is None:
            counts["original_unqualified_filename"] += 1
            resolve_unqualified(name, path, side="original", symbols_table=original_symbols, embed_table=original_embeds)
        elif identity not in original_symbols:
            counts["original_missing_exact_symbol"] += 1
            gaps.append({"kind": "original_missing_exact_symbol", "file": name, "identity": list(identity)})
        else:
            counts["original_exact_symbol_join"] += 1

    for name, path in sorted(edited_images.items()):
        counts["edited_image_files"] += 1
        if name in USER_TEST_FIXTURES:
            counts["edited_user_test_fixture_excluded"] += 1
            exclusions.append({"file": name, **USER_TEST_FIXTURES[name]})
            continue

        if name not in original_images:
            counts["edited_only_images"] += 1
        identity = identity_for_name(name)
        if identity is not None:
            if identity not in edited_symbols:
                counts["edited_missing_exact_symbol"] += 1
                gaps.append({"kind": "edited_missing_exact_symbol", "file": name, "identity": list(identity)})
            else:
                counts["edited_exact_symbol_join"] += 1
            continue

        counts["edited_unqualified_filename"] += 1
        if name in SUPPLEMENTAL_SOURCE_ASSETS:
            disposition = SUPPLEMENTAL_SOURCE_ASSETS[name]
            related = disposition["related_export"]
            related_identity = identity_for_name(related)
            wrapper = EDITED_EXPORT / disposition["wrapper"]
            callsite = EDITED_EXPORT / disposition["runtime_callsite"]
            wrapper_text = wrapper.read_text(encoding="utf-8-sig", errors="replace") if wrapper.is_file() else ""
            callsite_text = callsite.read_text(encoding="utf-8-sig", errors="replace") if callsite.is_file() else ""
            wrapper_embed = EMBED_CLASS.search(wrapper_text)
            wrapper_package = PACKAGE.search(wrapper_text)
            wrapper_qualified_class = ""
            if wrapper_embed is not None:
                package_name = wrapper_package.group(1) if wrapper_package else ""
                wrapper_qualified_class = (
                    f"{package_name}.{wrapper_embed.group('class')}" if package_name else wrapper_embed.group("class")
                )
            embed_ok = related_identity in edited_symbols and related in edited_images and related in edited_embeds
            class_embed_ok = (
                wrapper_embed is not None
                and Path(wrapper_embed.group("asset")).name == related
                and wrapper_qualified_class == disposition["qualified_class"]
                and wrapper_qualified_class in edited_embeds.get(related, set())
            )
            runtime_call_ok = disposition["runtime_call"] in callsite_text
            direct_embed = name in edited_embeds
            if not (embed_ok and class_embed_ok and runtime_call_ok and not direct_embed):
                gaps.append({
                    "kind": "edited_supplemental_disposition_evidence_failed",
                    "file": name,
                    "related_export": related,
                    "wrapper_found": wrapper.is_file(),
                    "callsite_found": callsite.is_file(),
                    "related_symbol_registered": related_identity in edited_symbols,
                    "related_export_embedded_by_class": class_embed_ok,
                    "runtime_call_found": runtime_call_ok,
                    "direct_embed_found": direct_embed,
                })
                continue
            counts["edited_supplemental_unembedded_assets"] += 1
            resolutions.append({
                "kind": disposition["kind"],
                "side": "edited",
                "file": name,
                "source": str(path),
                "related_export": related,
                "character_id": disposition["character_id"],
                "qualified_class": disposition["qualified_class"],
                "wrapper": str(wrapper),
                "runtime_callsite": str(callsite),
                "runtime_call": disposition["runtime_call"],
                "direct_embed": False,
                "reason": disposition["reason"],
            })
            continue

        resolve_unqualified(name, path, side="edited", symbols_table=edited_symbols, embed_table=edited_embeds)

    if len(original_images) != 1454 or len(edited_images) != 1456:
        gaps.append({"kind": "count_drift", "original": len(original_images), "edited": len(edited_images)})

    report = {
        "scope": (
            "Original exports and edited source images are joined by exact symbol identity, "
            "resolved through exact ActionScript Embed classes, explicitly dispositioned, "
            "or listed as unresolved. User-confirmed Minion Maker test output is excluded "
            "from reference-game coverage and preserved in the source inventory."
        ),
        "counts": dict(sorted(counts.items())),
        "resolutions": resolutions,
        "excluded_user_test_fixtures": exclusions,
        "gaps": gaps,
    }
    OUTPUT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"counts": report["counts"], "resolution_count": len(resolutions), "excluded_fixture_count": len(exclusions), "gap_count": len(gaps), "gap_preview": gaps[:12]}, indent=2))


if __name__ == "__main__":
    main()
